# Generated by Django 3.0.4 on 2020-10-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localization',
            name='lat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='localization',
            name='longit',
            field=models.IntegerField(),
        ),
    ]
