# Generated by Django 3.0.4 on 2020-10-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201024_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherperevent',
            name='eventId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weatherperevent',
            name='weatherId',
            field=models.IntegerField(),
        ),
    ]
